name: sparkle_flutter
description: "A new Flutter plugin project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.8.0
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  pigeon: ^25.3.2

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: SparkleFlutterPlugin
